### ISSUE TITLE
MySQL bug

### ISSUE THREAD

**Issue by Habibullah-pythoner** [Datcyx/NGG-V3--REFIX-#1]
Hello there, great work mate.
But there is a bug, or seems like it. When I am running my server locally and MySQL server is running locally it works fine, But when I deploy it to a server that uses a remote MySQL server, it gives this error
`[17:52:41] [MySQL] (Main Pipelines) Connecting to localhost...
[17:52:41] [MySQL] (MainPipeline) Fatal Error! Could not connect to MySQL: Host localhost - DB: ngrpc - User: root
[17:52:41] [MySQL] Note: Make sure that you have provided the correct connection credentials.
[17:52:41] [MySQL] Error number: 2059`

if full "server_log.txt" is required, please let me know.

NOTE: I DID UPDATE THE FILE "mysql.cfg" TO THE WORKING MySQL SERVER, AND THE SERVER SHOULDN'T ATTEMPT CONNECTING TO LOCALHOST AT ALL IN FIRST PLACE.

thanks

**Comment by Datcyx** [comment]
Hi, it seems you have a mistake on MySQL.cfg, please make sure you modified it on scrip files/MySQL.cf and make sure you've changed that localhost to the correct IP of your remote host

**Comment by Datcyx** [comment]
Make sure also you configure the firewall of your server

**Comment by Datcyx** [comment]
Or maybe you mistakenly modified the MySQL.cfg , it is located on the script files folder, those cfgs on the home folder, I accidentally merge it that's why there's a lot of cfgs there

**Comment by Datcyx** [comment]
Here's the test server that I created 

20.205.60.132:7777

**Comment by Datcyx** [comment]
Configure your server firewall

**Comment by Habibullah-pythoner** [comment]
Hey, thanks for the reply.
Changing scriptfiles/mysql file did solve the issue

Regards
