### ISSUE TITLE
Logging in as admin or adding admin

### ISSUE THREAD

**Issue by Habibullah-pythoner** [Datcyx/NGG-V3--REFIX-#3]
Changing the AdminLVL at database table "accounts" to appropriate values causes the account non-playable.
I did change my account admin level to "99999" but when I try to log in, it kicks me out "Server closed connection".
but when I change it back to 0, everything works fine.

same issue when making admin in-game using cmd /sadmindd, it works fine till the player logs off, he won't be able to log back in

**Comment by Datcyx** [comment]
Hi have you downloaded the latelest game mode?

**Comment by Datcyx** [comment]
I updated it already, this happened because of the whitelist system on admin, I update the game mode and removed it, please download the latest upload

**Comment by Datcyx** [comment]
Have a good day

**Comment by Datcyx** [comment]
Please reply if it fixed already

**Comment by Habibullah-pythoner** [comment]
Hello, yes Thanks.
I updated the gamemode file and now it works fine.

Thanks for the great work
